version: '3'
services:
  freepbx:
    build: .
    ports:
      - "8080:80"
      - "3306:3306"
  # mysql:
  #   image: "mysql:5.7"
  #   environment:
  #     - MYSQL_DATABASE=freepbx
  #     - MYSQL_USER=freepbx
  #     - MYSQL_PASSWORD=freepbx
  #     - MYSQL_ROOT_PASSWORD=freepbx
  #     - MYSQL_DEBUG=false
  #   ports:
  #     - "3306:3306"
  #   # volumes:
  #   #   - /asterisk/mysql-data:/var/lib/mysql


